L1:(function initSiteData(globalScope) {
L2:  const LOCALES = {
L3:    EN: 'en',
L4:    CA: 'ca'
L5:  };
L6:
L7:  globalScope.SITE_DATA = {
L8:    terminal: {
L9:      files: {
L10:        email: { type: "link", text: "miqueltorner9@gmail.com\n", href: "mailto:miqueltorner9@gmail.com" },
L11:        cv: { type: "link", text: "Miquel_Torner_CV.pdf\n", href: "./docs/Miquel_Torner_CV.pdf" },
L12:        portfolio: { type: "link", text: "miquelt9.github.io/portfolio/\n", href: "https://miquelt9.github.io/portfolio/" },
L13:        posts: { type: "link", text: "miquelt9.github.io/portfolio/posts\n", href: "https://miquelt9.github.io/portfolio/posts" },
L14:        github: { type: "link", text: "github.com/miquelt9\n", href: "https://github.com/miquelt9" },
L15:        linkedin: { type: "link", text: "linkedin.com/in/miqueltv/\n", href: "https://www.linkedin.com/in/miqueltv/" },
L16:        devpost: { type: "link", text: "devpost.com/miqueltorner9\n", href: "https://www.devpost.com/miqueltorner9" },
L17:      },
L18:      hiddenFiles: [".", "..", "snake.sh", "goose.sh", "virus.sh"],
L19:      links: {
L20:        github: "https://github.com/miquelt9",
L21:        linkedin: "https://www.linkedin.com/in/miqueltv/",
L22:        devpost: "https://devpost.com/miqueltorner9",
L23:        cv: "./docs/Miquel_Torner_CV.pdf",
L24:        portfolio: "https://miquelt9.github.io/portfolio/",
L25:        posts: "https://miquelt9.github.io/portfolio/posts",
L26:      },
L27:      about: {
L28:        intro: "Hi I'm Miquel!",
L29:        bullets: [
L30:          "Informatics Engineering graduate from Barcelona School of Informatics (FIB), UPC",
L31:          "Apart from programming, I love cooking and hiking!",
L32:        ],
L33:        locales: ["English", "Catalan", "Spanish"],
L34:      },
L35:    },
L36:    content: {
L37:      [LOCALES.EN]: {
L38:        aboutDesktop:
L39:          '<div class="properties"><img src="images/meOnPC.png"><div class="txt">System: <br>&nbsp; Miquel Torner Viñals <br><br>Registered to: <br>&nbsp; Barcelona School of Informatics, Polythecnic University of Catalonia <br>&nbsp; Bachelor\'s degree in Informatics Engineering (major in computing)<br><br>Hi, I\'m Miquel! I love programming, cooking, hiking and traveling. <br>Thanks for checking out my website :)</div></div>',
L40:        aboutMobile:
L41:          '<div class="properties" style="padding: 10px; text-align: justify;">System: <br>&nbsp; Miquel Torner Viñals <br>&nbsp;<br>Registered to: <br>&nbsp; · FIB, Polythecnic University of Catalonia <br>&nbsp; · Bachelor\'s degree in Informatics Engineering (major in computing)<br><br>&nbsp;<br>Hi, I\'m Miquel! I love programming, cooking, hiking and traveling. <br>Thanks for checking out my website! <br>&nbsp;<br>(Use a desktop/laptop for the full interactive experience)</div>',
L42:        projectsDesktop:
L43:          '• <strong><a href="https://miquelt9.github.io/portfolio/posts/personal/otaniemi-tracker-bot/" class="clickable" style="color: black;">Otaniemi tracker bot</a></strong> &nbsp; <a class="clickable" href="https://github.com/miquelt9/otaniemitrackerbot"><u class="clickable">Github</u></a> &nbsp; <a class="clickable" href="https://t.me/otaniemitrackerbot"><u class="clickable">Telegram</u></a> <br>&nbsp; A Telegram bot that tracks the buy/sell group (Erasmus+ 2023)<br><br>• <strong><a href="https://miquelt9.github.io/portfolio/posts/competitions/royalhackawayv6/" class="clickable" style="color: black;">Plushistics</a></strong> &nbsp; <a class="clickable" href="https://devpost.com/software/plushistics"><u class="clickable">Devpost</u></a><br>&nbsp; A 2D interactive simulator which uses planning algorithms to optimize routes (RoyalHackaway 2023)<br><br>• <strong><a href="https://miquelt9.github.io/portfolio/posts/college/falconexplorer/" class="clickable" style="color: black;">Falcon Explorer</a></strong> &nbsp; <a class="clickable" href="https://github.com/miquelt9/PROP-FIB"><u class="clickable">Github</u></a><br>&nbsp; A file explorer program with a file editor on it (Course Project 2022)<br><br>• <strong><a href="https://miquelt9.github.io/portfolio/posts/competitions/funcions-numerables/" class="clickable" style="color: black;">Chip-Chips</a></strong> &nbsp; <a class="clickable" href="https://devpost.com/software/chip-chips"><u class="clickable">Devpost</u></a><br>&nbsp; An algorithm that minimizes the average length of chains that connect pins in a chip (DatathonFME 2022)<br><br>• <strong><a href="https://miquelt9.github.io/portfolio/posts/competitions/hackupc2021/" class="clickable" style="color: black;">SpaceShooter</a></strong> &nbsp; <a class="clickable" href="https://devpost.com/software/spaceshooter-5hi4of"><u class="clickable">Devpost</u></a> <div class="gamelink clickable" onclick="openWindow(\'spaceshooter\')">Try it now!</div><br>&nbsp; A 2D single player game based in the arcada Asteroids using Unity (HackUPC 2021)<br><br>Check more at my <strong><a href="https://miquelt9.github.io/portfolio/posts/" class="clickable">portfolio</a></strong>!',
L44:        projectsMobile:
L45:          '• <strong><a href="https://miquelt9.github.io/portfolio/posts/personal/otaniemi-tracker-bot/" class="clickable" style="color: black;">Otaniemi tracker bot</a></strong> &nbsp; <a class="clickable" href="https://github.com/miquelt9/otaniemitrackerbot"><u class="clickable">Github</u></a> &nbsp; <a class="clickable" href="https://t.me/otaniemitrackerbot"><u class="clickable">Telegram</u></a> <br>&nbsp; A Telegram bot that tracks the buy/sell group (Erasmus+ 2023)<br><br>• <strong><a href="https://miquelt9.github.io/portfolio/posts/competitions/royalhackawayv6/" class="clickable" style="color: black;">Plushistics</a></strong> &nbsp; <a class="clickable" href="https://devpost.com/software/plushistics"><u class="clickable">Devpost</u></a><br>&nbsp; A 2D interactive simulator which uses planning algorithms to optimize routes (RoyalHackaway 2023)<br><br>• <strong><a href="https://miquelt9.github.io/portfolio/posts/college/falconexplorer/" class="clickable" style="color: black;">Falcon Explorer</a></strong> &nbsp; <a class="clickable" href="https://github.com/miquelt9/PROP-FIB"><u class="clickable">Github</u></a><br>&nbsp; A file explorer program with a file editor on it (Course Project 2022)<br><br>• <strong><a href="https://miquelt9.github.io/portfolio/posts/competitions/funcions-numerables/" class="clickable" style="color: black;">Chip-Chips</a></strong> &nbsp; <a class="clickable" href="https://devpost.com/software/chip-chips"><u class="clickable">Devpost</u></a><br>&nbsp; An algorithm that minimizes the average length of chains that connect pins in a chip (DatathonFME 2022)<br><br>• <strong><a href="https://miquelt9.github.io/portfolio/posts/competitions/hackupc2021/" class="clickable" style="color: black;">SpaceShooter</a></strong> &nbsp; <a class="clickable" href="https://devpost.com/software/spaceshooter-5hi4of"><u class="clickable">Devpost</u></a> <div class="gamelink clickable" onclick="openWindow(\'spaceshooter\')">Try it now!</div><br>&nbsp; A 2D single player game based in the arcada Asteroids using Unity (HackUPC 2021)<br><br>Check more at my <strong><a href="https://miquelt9.github.io/portfolio/posts/" class="clickable">portfolio</a></strong>!',
L46:        contactDesktop:
L47:          '<a class="clickable" href="mailto:miqueltorner9@gmail.com"> miqueltorner9@gmail.com </a> <br><a class="clickable" href="https://www.linkedin.com/in/miqueltv/"> LinkedIn </a> <br><a class="clickable" href="https://github.com/miquelt9"> GitHub </a> <br><a class="clickable" href="https://miquelt9.github.io/portfolio"> Portfolio </a> <br><a class="windowslink clickable" onclick="showWindow(\'cvbox\')" style="padding-left: 0%;">Check my CV!</a>',
L48:        contactMobile:
L49:          '<a href="mailto:miqueltorner9@gmail.com"> miqueltorner9@gmail.com </a> <br><a href="https://www.linkedin.com/in/miqueltv/"> LinkedIn </a> <br><a href="https://github.com/miquelt9"> GitHub </a> <br><a class="clickable" href="https://miquelt9.github.io/portfolio"> Portfolio </a> <br><a href="./docs/Miquel_Torner_CV.pdf" target="_blank">Check my CV!</a>',
L50:      },
L51:      [LOCALES.CA]: {
L52:        aboutDesktop:
L53:          '<div class="properties"><img src="images/meOnPC.png"><div class="txt">Sistema: <br>&nbsp; Miquel Torner Viñals <br><br>Registrat a: <br>&nbsp; Facultat d\'Informàtica de Barcelona, Universitat Politècnica de Catalunya <br>&nbsp; Grau en Enginyeria Informàtica (especialitat en computació)<br><br>Hola, sóc en Miquel! M\'encanta la programació, cuinar, fer senderisme i viatjar. <br>Gràcies per visitar la meva web :)</div></div>',
L54:        aboutMobile:
L55:          '<div class="properties" style="padding: 10px; text-align: justify;">Sistema: <br>&nbsp; Miquel Torner Viñals <br>&nbsp;<br>Registrat a: <br>&nbsp; · FIB, Universitat Politècnica de Catalunya <br>&nbsp; · Grau en Enginyeria Informàtica (especialitat en computació)<br><br>&nbsp;<br>Hola, sóc en Miquel! M\'encanta la programació, cuinar, fer senderisme i viatjar. <br>Gràcies per visitar la meva web! <br>&nbsp;<br>(Fes servir un ordinador per a l\'experiència interactiva completa)</div>',
L56:        projectsDesktop:
L57:          '• <strong><a href="https://miquelt9.github.io/portfolio/posts/personal/otaniemi-tracker-bot/" class="clickable" style="color: black;">Otaniemi tracker bot</a></strong> &nbsp; <a class="clickable" href="https://github.com/miquelt9/otaniemitrackerbot"><u class="clickable">Github</u></a> &nbsp; <a class="clickable" href="https://t.me/otaniemitrackerbot"><u class="clickable">Telegram</u></a> <br>&nbsp; Un bot de Telegram que rastreja el grup de compra/venda (Erasmus+ 2023)<br><br>• <strong><a href="https://miquelt9.github.io/portfolio/posts/competitions/royalhackawayv6/" class="clickable" style="color: black;">Plushistics</a></strong> &nbsp; <a class="clickable" href="https://devpost.com/software/plushistics"><u class="clickable">Devpost</u></a><br>&nbsp; Un simulador interactiu 2D que utilitza algorismes de planificació per optimitzar rutes (RoyalHackaway 2023)<br><br>• <strong><a href="https://miquelt9.github.io/portfolio/posts/college/falconexplorer/" class="clickable" style="color: black;">Falcon Explorer</a></strong> &nbsp; <a class="clickable" href="https://github.com/miquelt9/PROP-FIB"><u class="clickable">Github</u></a><br>&nbsp; Un programa explorador de fitxers amb un editor de fitxers (Projecte de curs 2022)<br><br>• <strong><a href="https://miquelt9.github.io/portfolio/posts/competitions/funcions-numerables/" class="clickable" style="color: black;">Chip-Chips</a></strong> &nbsp; <a class="clickable" href="https://devpost.com/software/chip-chips"><u class="clickable">Devpost</u></a><br>&nbsp; Un algorisme que minimitza la longitud mitjana de les cadenes que connecten pins en un xip (DatathonFME 2022)<br><br>• <strong><a href="https://miquelt9.github.io/portfolio/posts/competitions/hackupc2021/" class="clickable" style="color: black;">SpaceShooter</a></strong> &nbsp; <a class="clickable" href="https://devpost.com/software/spaceshooter-5hi4of"><u class="clickable">Devpost</u></a> <div class="gamelink clickable" onclick="openWindow(\'spaceshooter\')">Prova-ho ara!</div><br>&nbsp; Un joc 2D per a un sol jugador basat en l\'arcade Asteroids utilitzant Unity (HackUPC 2021)<br><br>Mira més al meu <strong><a href="https://miquelt9.github.io/portfolio/posts/" class="clickable">portfoli</a></strong>!',
L58:        projectsMobile:
L59:          '• <strong><a href="https://miquelt9.github.io/portfolio/posts/personal/otaniemi-tracker-bot/" class="clickable" style="color: black;">Otaniemi tracker bot</a></strong> &nbsp; <a class="clickable" href="https://github.com/miquelt9/otaniemitrackerbot"><u class="clickable">Github</u></a> &nbsp; <a class="clickable" href="https://t.me/otaniemitrackerbot"><u class="clickable">Telegram</u></a> <br>&nbsp; Un bot de Telegram que rastreja el grup de compra/venda (Erasmus+ 2023)<br><br>• <strong><a href="https://miquelt9.github.io/portfolio/posts/competitions/royalhackawayv6/" class="clickable" style="color: black;">Plushistics</a></strong> &nbsp; <a class="clickable" href="https://devpost.com/software/plushistics"><u class="clickable">Devpost</u></a><br>&nbsp; Un simulador interactiu 2D que utilitza algorismes de planificació per optimitzar rutes (RoyalHackaway 2023)<br><br>• <strong><a href="https://miquelt9.github.io/portfolio/posts/college/falconexplorer/" class="clickable" style="color: black;">Falcon Explorer</a></strong> &nbsp; <a class="clickable" href="https://github.com/miquelt9/PROP-FIB"><u class="clickable">Github</u></a><br>&nbsp; Un programa explorador de fitxers amb un editor de fitxers (Projecte de curs 2022)<br><br>• <strong><a href="https://miquelt9.github.io/portfolio/posts/competitions/funcions-numerables/" class="clickable" style="color: black;">Chip-Chips</a></strong> &nbsp; <a class="clickable" href="https://devpost.com/software/chip-chips"><u class="clickable">Devpost</u></a><br>&nbsp; Un algorisme que minimitza la longitud mitjana de les cadenes que connecten pins en un xip (DatathonFME 2022)<br><br>• <strong><a href="https://miquelt9.github.io/portfolio/posts/competitions/hackupc2021/" class="clickable" style="color: black;">SpaceShooter</a></strong> &nbsp; <a class="clickable" href="https://devpost.com/software/spaceshooter-5hi4of"><u class="clickable">Devpost</u></a> <div class="gamelink clickable" onclick="openWindow(\'spaceshooter\')">Prova-ho ara!</div><br>&nbsp; Un joc 2D per a un sol jugador basat en l\'arcade Asteroids utilitzant Unity (HackUPC 2021)<br><br>Mira més al meu <strong><a href="https://miquelt9.github.io/portfolio/posts/" class="clickable">portfoli</a></strong>!',
L60:        contactDesktop:
L61:          '<a class="clickable" href="mailto:miqueltorner9@gmail.com"> miqueltorner9@gmail.com </a> <br><a class="clickable" href="https://www.linkedin.com/in/miqueltv/"> LinkedIn </a> <br><a class="clickable" href="https://github.com/miquelt9"> GitHub </a> <br><a class="clickable" href="https://miquelt9.github.io/portfolio"> Portfoli </a> <br><a class="windowslink clickable" onclick="showWindow(\'cvbox\')" style="padding-left: 0%;">Mira el meu CV!</a>',
L62:        contactMobile:
L63:          '<a href="mailto:miqueltorner9@gmail.com"> miqueltorner9@gmail.com </a> <br><a href="https://www.linkedin.com/in/miqueltv/"> LinkedIn </a> <br><a href="https://github.com/miquelt9"> GitHub </a> <br><a class="clickable" href="https://miquelt9.github.io/portfolio"> Portfoli </a> <br><a href="./docs/Miquel_Torner_CV.pdf" target="_blank">Mira el meu CV!</a>',
L64:      }
L65:    },
L66:  };
L67:})(window);

